### ISSUE TITLE
Provide rdf/xml serialization of InfoSecSoS_Ontology

### ISSUE THREAD

**Issue by SArndt-TIB** [rmbelmont/InfoSecSoS#1]
Hello,

I was wondering whether you could provide further serializations of the InfoSecSoS_Ontology, in particular rdf/xml?

Thanks for considering :-)

Best wishes

Susanne

**Comment by rmbelmont** [comment]
Hi Susanne,

Below is the inserted InfoSecSoS.rdf ontology.

Greetings,

Roberto Dias

**Comment by SArndt-TIB** [comment]
Thanks, Roberto :-) Much appreciated!
